#!/bin/bash
#Repositories
pamac install dia firefox gimp inkscape kdenlive keepassxc krita neovim obs-studio signal-desktop torbrowser-launcher caffeine-ng etcher neofetch gnome-shell-extension-material-shell
#AUR
pamac build freetube-bin iridium-rpm vscodium-bin bpytop
